# Generated by Django 2.2 on 2021-08-03 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dean', '0002_doctor'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bkd_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Booklist')),
                ('doct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dean.doctor')),
            ],
        ),
    ]
